eureka:
  instance:
    hostname: localhost
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/mysqltnd
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
         json:
          trusted:
           packages: com.company.*
    consumer:
      auto-offset-reset: earliest
      key-deserializer:
        org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer:
        org.springframework.kafka.support.serializer.JsonDeserializer
      bootstrap-servers:
      - localhost:9092
      properties:
        spring:
         json:
          trusted:
           packages: com.company.*
resilience4j:
  circuitbreaker:
    instances: 
     cabCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10   
  retry:
    instances:
      cabCB:
        max-attempts: 5
        wait-duration: 5s
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - health
  endpoint:
    health:
      show-details: always
